### PR TITLE
patch popularity in all admin layers using neighborhoods

### LINKED ISSUE #4: Compute admin0, admin1, admin2 popularity scores
As we know ```localadmin``` ```localities``` and ```neighborhoods``` have popularity ratings. We should look into using this information and saving it to ```admin0```, ```admin1``` and ```admin2``` so that a point in a popular state is scored higher even though it doesnt intersect in a popular neighborhood. 

This [issue](https://github.com/pelias/admin-lookup/issues/5) deals with adding using popularity information while we perform admin lookup for each geospatial point with a lat/lon. With this patch we would be able to perform the same thing for all the points!

### PR DESCRIPTION
**Pull request by sevko**
Add scripts to propagate popularity values from `qs_neighborhoods` to all other administrative levels, as per #4 .

fixes #4

### CODE REVIEW

**Comment by sevko** [comment]
Running sanity tests locally (these predictable take a *long* time), but it should be good to go. @hkrishna , can you take a look at the SQL?

**Comment by dianashk** [comment]
+1
Are those sanity tests complete? How did they go?

**Comment by sevko** [comment]
Kicked off another one this morning, so this is no-go until it finishes. The query is taking absurdly long for `qs_adm0`.

**Comment by sevko** [comment]
Right, just finished. LGTM.

@hkrishna , can you check the queries as well?

**Comment by hkrishna** [comment]
+1

**Pull request merged**
